Fix error unregistering addon
Error caused by removing non-existing property.

Example error:
```
Error: Traceback (most recent call last):
  File "\Blender\4.3\scripts\modules\addon_utils.py", line 562, in disable
    mod.unregister()
  File "\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\spring_bones.py", line 867, in unregister
    del bpy.types.Object.sb_collide
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'Object' has no attribute 'sb_collide'
```